[package]
name = "photo_app"
version = "0.1.0"
edition = "2024"

[dependencies]
actix-web = "4"
sqlx = { version = "0.7", features = ["runtime-tokio", "tls-native-tls", "postgres"] }
dotenvy = "0.15"
